server:
  port: 7800
spring:
  application:
    name: config-app
  boot:
    admin:
      client:
        url: http://localhost:7900
  cloud:
    config:
      server:
        git:
          uri: https://github.com/etiamayedze/reactive-microservices-config

management.endpoints.web.exposure.include: '*'
